blank_issues_enabled: false
contact_links:
  - name: Website from Titus Kirch
    url: https://tkirch.dev
    about: Please ask and answer questions here.
  - name: Discord server from Titus Kirch
    url: https://discord.tkirch.dev
    about: Please ask and answer questions here.
